### ISSUE TITLE
v0.71f doesn't work properly

### ISSUE THREAD

**Issue by croutonn** [dmorigin/se_mod_vis#1]
Hi, thanks for the cool script!!😍

I don't know the detailed condition (in the vanilla world) , but there is a problem that the LCD does not update from "Initilize screen" with v0.71f.
There was no problem with v0.71e.
Please verify this.

**Comment by dmorigin** [comment]
I use this version at a couple of constructions without any issues. Is there a red line on your console or an exception? To isolate a possible issue remove some of the displays to find that one that makes trouble.

**Comment by croutonn** [comment]
Unfortunately, there is no exception.
The console displays a warning that says "No data accessor defined" but when I logged it seemed to read and parse the custom data correctly, so I don't think this is the cause of the problem.

Not just me, but one of my friends doesn't seem to work the same way, but I don't know what the conditions are, and it seems difficult to reproduce ...😩

**Comment by dmorigin** [comment]
I was able to reproduce the issue. But I don't understand what is happen. The system dosen't execute the jobs in the queue. That's strange. The system isn't in a state to jump over that process. So I'm working on it to solve this issue.

**Comment by dmorigin** [comment]
Oh man :D I have found the issue. This happen in some special cases, where the last job was not executed. Is this last job is the render job, then the screen isn't updated. I have fixed it with version 0.71g
