### ISSUE TITLE
"replace" don't work

### ISSUE THREAD

**Issue by Norax64** [dmorigin/se_mod_vis#2]
// ---------------------------
// Start Screen
// ---------------------------
screen:0
bgcolor:0,0,0

// -----------------------
// Start Graph
// -----------------------
graphic:text:value
font:DEBUG:1.0:255,255,255
position:0.5,0.5:r
check:property:Reactor:false:OnOff
replace:0.0:OFF
replace:1.0:ON

Error : Invalid display provider config: replace, 0.0

But, the command "visibility" work fine.

Edit: I found that "replace" work with graphic:list but not with graphic:text If it's normal we can close issue

**Comment by dmorigin** [comment]
The graphic "text" don't support the setting "replace". The setting "replace" is part of the graphic "list".
