### ISSUE TITLE
Airvent + graphic bar

### ISSUE THREAD

**Issue by Norax64** [dmorigin/se_mod_vis#4]
Hi DM, the DC airvent don't allow gradient ? Here, the progress bar don't work

![airvent](https://user-images.githubusercontent.com/63313449/91633915-861fb500-e9ec-11ea-90c3-87d7e4397269.png)

$fan:bl.bs.aeration

screen:0
bgcolor:0,0,0
refresh:1.0

graphic:text:oxygenlevel
position:0.7,0.7:r
font::1.2
alignment:center
check:airvent:$(fan):false
text:%oxygenlevel%
dcrefresh:1.0

graphic:bar:oxygenlevel
position:0.175,0.55:r
size:0.15,0.7:r
check:airvent:$(fan):false
style:tiles:0:14:7:a:SquareSimple
border:Simple:2:2:a:0,88,151
gradient:0.0:255,0,0
gradient:0.2:255,100,0
gradient:0.5:255,255,0
gradient:0.9:0,255,0
dcrefresh:1.0

**Comment by dmorigin** [comment]
The DA returning always 0.0. Fixed in Version 0.72b.
